=== biosp4rk/mf-zm-info/schema/data.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "$ref": "urn:definitions#/definitions/Name"
            },
            "desc": {
                "$ref": "urn:definitions#/definitions/Description"
            },
            "type": {
                "$ref": "urn:definitions#/definitions/Type"
            },
            "count": {
                "$ref": "urn:definitions#/definitions/RegionInt"
            },
            "addr": {
                "$ref": "urn:definitions#/definitions/RegionInt"
            },
            "cat": {
                "$ref": "urn:definitions#/definitions/Category"
            },
            "comp": {
                "$ref": "urn:definitions#/definitions/Compression"
            },
            "loc": {
                "$ref": "urn:definitions#/definitions/Location"
            }
        },
        "required": ["name", "type", "addr", "loc"],
        "additionalProperties": false
    }
}

=== biosp4rk/mf-zm-info/json/zm/ram.json
[{"name": "gClipdataCollisionTypes", "type": "u8", "count": 1024, "addr": 33562624, "loc": "include/structs/room.h:123"}, {"name": "gClipdataCollisionTypes_Tilemap", "type": "u8", "count": 512, "addr": 33563648, "loc": "include/structs/room.h:124"}, {"name": "gClipdataBehaviorTypes", "type": "u16", "count": 1024, "addr": 33566720, "loc": "include/structs/room.h:126"}, {"name": "gClipdataBehaviorTypes_Tilemap", "type": "u16", "count": 512, "addr": 33568768, "loc": "include/structs/room.h:127"}, {"name": "gTilemap", "type": "u16", "count": 1024, "addr": 33570816, "loc": "include/structs/room.h:129"}, {"name": "gCommonTilemap", "type": "u16", "count": 1024, "addr": 33579008, "loc": "include/structs/room.h:131"}, {"name": "gDecompBg3Map", "type": "u16", "count": 2048, "addr": 33583104, "loc": "include/structs/room.h:137"}, {"name": "gHazeValues", "type": "u16", "count": 1280, "addr": 33710848, "loc": "include/structs/haze.h:37"}, {"name": "gPreviousHazeValues", "type": "u16", "count": 1280, "addr": 33713408, "loc": "include/structs/haze.h:38"}, {"name": "gCurrentCharacterGfx", "type": "u32", "count": 32, "addr": 33715968, "loc": "include/structs/text.h:28"}, {"name": "gMakeSolidBlocks", "type": "u16", "count": 64, "addr": 33716096, "loc": "include/structs/block.h:69"}, {"name": "gDecompClipdataMap", "type": "u16", "count": 1024, "addr": 33716224, "loc": "include/structs/room.h:133"}, {"name": "gDecompBg0Map", "type": "u16", "count": 6144, "addr": 33728512, "loc": "include/structs/room.h:134"}, {"name": "gDecompBg1Map", "type": "u16", "count": 6144, "addr": 33740800, "loc": "include/structs/room.h:135"}, {"name": "gDecompBg2Map", "type": "u16", "count": 6144, "addr": 33753088, "loc": "include/structs/room.h:136"}, {"name": "gMinimapTilesWithObtainedItems", "type": "u32", "count": 256, "addr": 33765376, "loc": "include/structs/minimap.h:28"}, {"name": "gDecompressedMinimapVisitedTiles", "type": "u16", "count": 1024, "addr": 33767424, "loc": "include/structs/minimap.h:29"}, {"name": "gDecompressedMinimapData", "type": "u16", "count": 1024, "addr": 33769472, "loc": "include/structs/minimap.h:30"}, {"name": "gUnk_02035400", "type": "u16", "addr": 33772544, "loc": "include/temp_globals.h:56"}, {"name": "gNeverReformBlocks", "type": "u8 [0x200]", "count": 8, "addr": 33774592, "loc": "include/structs/bg_clip.h:83"}, {"name": "gItemsCollected", "type": "struct ItemInfo [0x40]", "count": 8, "addr": 33778688, "loc": "include/structs/bg_clip.h:82"}, {"name": "gVisitedMinimapTiles", "type": "u32", "count": 256, "addr": 33780736, "loc": "include/structs/minimap.h:31"}, {"name": "gEventsTriggered", "type": "u32", "count": 8, "addr": 33783296, "loc": "include/event.h:13"}, {"name": "gMinimapTilesGfx", "type": "u32", "count": 120, "addr": 33783328, "loc": "include/structs/minimap.h:32"}, {"name": "gSram", "type": "struct Sram", "addr": 33783808, "loc": "include/structs/save_file.h:254"}, {"name": "gSramDemoInputData", "type": "u16", "count": 256, "addr": 33812608, "loc": "include/structs/save_file.h:250"}, {"name": "gSramDemoInputDuration", "type": "u16", "count": 256, "addr": 33813120, "loc": "include/structs/save_file.h:251"}, {"name": "gDebugMode", "type": "u8", "addr": 50331648, "loc": "include/structs/game_state.h:33"}, {"name": "gBootDebugActive", "type": "u8", "cat": "bool", "addr": 50331649, "loc": "include/structs/game_state.h:34"}, {"name": "gFrameCounter16Bit", "type": "u16", "addr": 50331650, "loc": "include/structs/game_state.h:48"}, {"name": "gStereoFlag", "type": "u8", "addr": 50331652, "loc": "include/structs/audio.h:266"}, {"name": "gSubGameModeStage", "type": "u8", "addr": 50331653, "loc": "include/structs/game_state.h:59"}, {"name": "gWrittenToBldalpha", "type": "u16", "addr": 50331654, "loc": "include/structs/display.h:28"}, {"name": "gWrittenToBldcnt_Internal", "type": "u16", "addr": 50331656, "loc": "include/structs/display.h:24"}, {"name": "gWrittenToDispcnt", "type": "u16", "addr": 50331658, "loc": "include/structs/display.h:38"}, {"name": "gWrittenToWinIn_H", "type": "u8", "addr": 50331662, "loc": "include/structs/display.h:39"}, {"name": "gWrittenToWinOut_L", "type": "u8", "addr": 50331663, "loc": "include/structs/display.h:40"}, {"name": "gBackdropColor", "type": "u16", "addr": 50331664, "loc": "include/structs/display.h:26"}, {"name": "gWrittenToBldy", "type": "s8", "addr": 50331666, "loc": "include/structs/display.h:31"}, {"name": "gFileScreenOptionsUnlocked", "type": "struct FileScreenOptionsUnlocked", "addr": 50331668, "loc": "include/structs/game_state.h:28"}, {"name": "gLanguage", "type": "Language", "addr": 50331680, "loc": "include/structs/game_state.h:50"}, {"name": "gGameCompletion", "type": "struct GameCompletion", "addr": 50331684, "loc": "include/structs/game_state.h:16"}, {"name": "gCompletedGameFlagCopy", "type": "u8", "addr": 50331688, "loc": "include/structs/game_state.h:63"}, {"name": "gMonochromeBgFading", "type": "MonochromeFading", "addr": 50331689, "loc": "include/structs/visual_effects.h:8"}, {"name": "gWhichBgPositionIsWrittenToBG3OFS", "type": "u8", "addr": 50331690, "loc": "include/structs/connection.h:116"}, {"name": "gSamusOnTopOfBackgrounds", "type": "u8", "addr": 50331691, "loc": "include/structs/samus.h:184"}, {"name": "gDifficulty", "type": "Difficulty", "addr": 50331692, "loc": "include/structs/game_state.h:49"}, {"name": "gUseMotherShipDoors", "type": "boolu8", "addr": 50331693, "loc": "include/structs/connection.h:118"}, {"name": "gTimeAttackFlag", "type": "boolu8", "addr": 50331694, "loc": "include/structs/game_state.h:40"}, {"name": "gCutsceneToSkip", "type": "u8", "addr": 50331695, "loc": "include/structs/cutscene.h:202"}, {"name": "gMusicTrackInfo", "type": "struct MusicTrackInfo", "addr": 50331696, "loc": "include/structs/audio.h:267"}, {"name": "gCurrentDemo", "type": "struct Demo", "addr": 50331704, "loc": "include/structs/demo.h:25"}, {"name": "gResetGame", "type": "boolu8", "addr": 50331708, "loc": "include/structs/game_state.h:51"}, {"name": "gDisableScrolling", "type": "u8", "addr": 50331709, "loc": "include/structs/game_state.h:38"}, {"name": "gSlowScrollingTimer", "type": "u16", "addr": 50331710, "loc": "include/structs/scroll.h:86"}, {"name": "gDisableMusic", "type": "boolu8", "addr": 50331712, "loc": "include/structs/game_state.h:35"}, {"name": "gDisableCutscenes_Unused", "type": "boolu8", "addr": 50331713, "loc": "include/structs/game_state.h:36"}, {"name": "gSkipDoorTransition", "type": "boolu8", "addr": 50331714, "loc": "include/structs/scroll.h:87"}, {"name": "gDisableSoftReset", "type": "boolu8", "addr": 50331715, "loc": "include/structs/game_state.h:32"}, {"name": "gCollectingTank", "type": "s8", "addr": 50331716, "loc": "include/structs/bg_clip.h:107"}, {"name": "gDisableAnimatedGraphicsTimer", "type": "u8", "addr": 50331717, "loc": "include/structs/animated_graphics.h:78"}, {"name": "gAnimatedGraphicsToUpdate", "type": "u16", "cat": "flags", "addr": 50331718, "loc": "include/structs/animated_graphics.h:79"}, {"name": "gDisableDoorAndTanks", "type": "u8", "addr": 50331720, "loc": "include/structs/bg_clip.h:108"}, {"name": "gDisablePause", "type": "s8", "addr": 50331721, "loc": "include/structs/game_state.h:37"}, {"name": "gHideHud", "type": "boolu8", "addr": 50331722, "loc": "include/structs/hud.h:26"}, {"name": "gShipLandingFlag", "type": "boolu8", "addr": 50331723, "loc": "include/structs/game_state.h:39"}, {"name": "gDisableClipdataChangingTransparency", "type": "u8", "addr": 50331724, "loc": "include/structs/bg_clip.h:109"}, {"name": "gDisableAnimatedPalette", "type": "s8", "addr": 50331725, "loc": "include/structs/animated_graphics.h:77"}, {"name": "gInGameCutscenesTriggered", "type": "u32", "count": 1, "cat": "flags", "addr": 50331728, "loc": "include/structs/in_game_cutscene.h:37"}, {"name": "gCurrentArea", "type": "Area", "addr": 50331732, "loc": "include/structs/connection.h:119"}, {"name": "gCurrentRoom", "type": "u8", "addr": 50331733, "loc": "include/structs/connection.h:121"}, {"name": "gLastDoorUsed", "type": "u8", "addr": 50331734, "loc": "include/structs/connection.h:122"}, {"name": "gLastDoorProperties", "type": "u8", "addr": 50331735, "loc": "include/structs/connection.h:123"}, {"name": "gDisplayLocationText", "type": "boolu8", "addr": 50331736, "loc": "include/structs/connection.h:124"}, {"name": "gMinimapX", "type": "u8", "addr": 50331737, "loc": "include/structs/minimap.h:23"}, {"name": "gMinimapY", "type": "u8", "addr": 50331738, "loc": "include/structs/minimap.h:24"}, {"name": "gNumberOfNeverReformBlocks", "desc": "Sets a clipdata block value using `gBgPointersAndDimensions` (order is width * y + x) pDecomp; pClipDecomp; NEVER_REFORM_BLOCK_INFO_SIZE) USE_EWRAM_SYMBOLS */", "type": "u8", "count": 8, "addr": 50331739, "loc": "include/structs/bg_clip.h:89"}, {"name": "gNumberOfItemsCollected", "type": "u8", "count": 8, "addr": 50331747, "loc": "include/structs/bg_clip.h:90"}, {"name": "gCurrentHazeValue", "type": "HazeValue", "addr": 50331755, "loc": "include/structs/haze.h:34"}, {"name": "gEffectYPosition", "type": "u16", "addr": 50331756, "loc": "include/structs/clipdata.h:54"}, {"name": "gEffectYPositionOffset", "type": "s16", "addr": 50331758, "loc": "include/structs/clipdata.h:55"}, {"name": "gScreenShakeXOffset", "type": "u8", "addr": 50331761, "loc": "include/structs/screen_shake.h:19"}, {"name": "gScreenShakeYOffset", "type": "u8", "addr": 50331762, "loc": "include/structs/screen_shake.h:20"}, {"name": "gScreenShakeRelated", "type": "u16", "addr": 50331764, "loc": "include/structs/screen_shake.h:21"}, {"name": "gDispcntBackup", "type": "u16", "addr": 50331766, "loc": "include/structs/display.h:37"}, {"name": "gSpriteset", "type": "u8", "addr": 50331768, "loc": "include/structs/room.h:139"}, {"name": "gCurrentClipdataAffectingAction", "type": "ClipdataAffectingAction", "addr": 50331769, "loc": "include/structs/clipdata.h:50"}, {"name": "gSpritesetEntryUsed", "type": "u8", "addr": 50331770, "loc": "include/structs/room.h:
