=== biosp4rk/mf-zm-info/schema/structs.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "$ref": "urn:definitions#/definitions/Name"
            },
            "desc": {
                "$ref": "urn:definitions#/definitions/Description"
            },
            "size": {
                "type": "integer"
            },
            "vars": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "$ref": "urn:definitions#/definitions/Name"
                        },
                        "desc": {
                            "$ref": "urn:definitions#/definitions/Description"
                        },
                        "type": {
                            "$ref": "urn:definitions#/definitions/Type"
                        },
                        "count": {
                            "$ref": "urn:definitions#/definitions/RegionInt"
                        },
                        "offset": {
                            "$ref": "urn:definitions#/definitions/RegionInt"
                        },
                        "bits": {
                            "type": "integer",
                            "minimum": 0
                        },
                        "cat": {
                            "$ref": "urn:definitions#/definitions/Category"
                        },
                        "comp": {
                            "$ref": "urn:definitions#/definitions/Compression"
                        }
                    },
                    "required": ["name", "type", "offset"],
                    "additionalProperties": false
                },
                "minItems": 1
            },
            "loc": {
                "$ref": "urn:definitions#/definitions/Location"
            }
        },
        "required": ["name", "size", "vars", "loc"],
        "additionalProperties": false
    }
}

=== biosp4rk/mf-zm-info/json/mf/structs.json
[{"name": "AbilityRamValue", "size": 8, "vars": [{"name": "beamStatus", "type": "u8", "offset": 0}, {"name": "weaponStatus", "type": "u8", "offset": 1}, {"name": "suitStatus", "type": "u8", "offset": 2}, {"name": "isSuit", "type": "u8", "offset": 3}, {"name": "messageNumber", "type": "u8", "offset": 4}, {"name": "soundEvent", "type": "u16", "offset": 6}], "loc": "include/structs/event.h:6"}, {"name": "AnimatedGraphicsData", "size": 8, "vars": [{"name": "type", "type": "u8", "offset": 0}, {"name": "framesPerState", "type": "u8", "offset": 1}, {"name": "numberOfStates", "type": "u8", "offset": 2}, {"name": "pGraphics", "type": "const u8* const", "offset": 4}], "loc": "include/structs/animated_graphics.h:36"}, {"name": "AnimatedGraphicsInfo", "size": 12, "vars": [{"name": "type", "type": "u8", "offset": 0}, {"name": "framesPerState", "type": "u8", "offset": 1}, {"name": "animationDurationCounter", "type": "u8", "offset": 2}, {"name": "numberOfStates", "type": "u8", "offset": 3}, {"name": "currentAnimationFrame", "type": "s8", "offset": 4}, {"name": "graphicsEntry", "type": "u8", "offset": 5}, {"name": "pGraphics", "type": "const u8*", "offset": 8}], "loc": "include/structs/animated_graphics.h:26"}, {"name": "AnimatedPaletteAndTileset", "size": 4, "vars": [{"name": "animatedPalette", "type": "u8", "offset": 0}, {"name": "animatedTileset", "type": "u8", "offset": 1}], "loc": "include/structs/animated_graphics.h:8"}, {"name": "AnimatedPaletteData", "size": 8, "vars": [{"name": "type", "type": "AnimatedPaletteType", "offset": 0}, {"name": "framesPerState", "type": "u8", "offset": 1}, {"name": "numberOfStates", "type": "u8", "offset": 2}, {"name": "pPalette", "type": "const u16*", "offset": 4}], "loc": "include/structs/animated_graphics.h:43"}, {"name": "AnimatedPaletteTiming", "size": 4, "vars": [{"name": "timer1", "type": "u8", "offset": 0}, {"name": "row1", "type": "s8", "offset": 1}, {"name": "timer2", "type": "u8", "offset": 2}, {"name": "row2", "type": "s8", "offset": 3}], "loc": "include/structs/animated_graphics.h:19"}, {"name": "AnimatedTiming", "size": 4, "vars": [{"name": "timer", "type": "u8", "offset": 0}, {"name": "frame", "type": "u8", "offset": 1}, {"name": "unk_2", "type": "u8", "offset": 2}], "loc": "include/structs/animated_graphics.h:13"}, {"name": "ArmCannonAnimData", "size": 8, "vars": [{"name": "pOffset", "type": "const s16*", "offset": 0}, {"name": "pOam", "type": "const u16*", "cat": "oam_frame", "offset": 4}], "loc": "include/structs/samus.h:147"}, {"name": "BackgroundPositions", "size": 20, "vars": [{"name": "bg", "type": "struct RawCoordsX", "count": 4, "offset": 0}, {"name": "doorTransition", "type": "struct RawCoordsX", "offset": 16}], "loc": "include/globals.h:154"}, {"name": "BackgroundsData", "size": 32, "vars": [{"name": "backgrounds", "type": "struct BackgroundsData__backgrounds", "count": 3, "offset": 0}, {"name": "pClipDecomp", "type": "u16*", "offset": 24}, {"name": "clipdataWidth", "type": "u16", "offset": 28}, {"name": "clipdataHeight", "type": "u16", "offset": 30}], "loc": "include/structs/bg_clip.h:45"}, {"name": "BackgroundsData__backgrounds", "size": 8, "vars": [{"name": "pDecomp", "type": "u16*", "offset": 0}, {"name": "width", "type": "u16", "offset": 4}, {"name": "height", "type": "u16", "offset": 6}], "loc": "include/structs/bg_clip.h:46"}, {"name": "Bg0Movement", "size": 8, "vars": [{"name": "type", "type": "u8", "offset": 0}, {"name": "counter", "type": "u8", "offset": 1}, {"name": "unused", "type": "u16", "offset": 2}, {"name": "xOffset", "type": "u16", "offset": 4}, {"name": "yOffset", "type": "u16", "offset": 6}], "loc": "include/structs/room.h:62"}, {"name": "Bg3Movement", "size": 8, "vars": [{"name": "direction", "type": "u8", "offset": 0}, {"name": "timer", "type": "u8", "offset": 1}, {"name": "leftToRightStage", "type": "u8", "offset": 2}, {"name": "xOffset", "type": "u16", "offset": 4}], "loc": "include/structs/room.h:53"}, {"name": "BlockBehavior", "size": 4, "vars": [{"name": "lifeType", "type": "BlockLifeType", "offset": 0}, {"name": "subType", "type": "BlockSubType", "offset": 1}, {"name": "type", "type": "BlockType", "offset": 2}, {"name": "isSpeedboost", "type": "u8", "offset": 3, "bits": 4}, {"name": "isBombChain", "type": "u8", "offset": 3, "bits": 4}], "loc": "include/structs/block.h:41"}, {"name": "BombChain", "size": 4, "vars": [{"name": "currentOffset", "type": "u8", "offset": 0}, {"name": "srcXPosition", "type": "u8", "offset": 1}, {"name": "srcYPosition", "type": "u8", "offset": 2}, {"name": "type", "type": "u8", "offset": 3, "bits": 3}, {"name": "padding", "type": "u8", "offset": 3, "bits": 3}, {"name": "negativeActive", "type": "u8", "offset": 3, "bits": 1}, {"name": "positiveActive", "type": "u8", "offset": 3, "bits": 1}], "loc": "include/structs/block.h:31"}, {"name": "BombChainReverseData", "size": 4, "vars": [{"name": "typeFlag", "type": "u8", "offset": 0}, {"name": "behavior", "type": "ClipBehavior", "offset": 2}], "loc": "include/structs/block.h:49"}, {"name": "BootDebugOptions", "size": 12, "vars": [{"name": "bld", "type": "union BootDebugOptions__bld", "offset": 0}, {"name": "bldalpha_evy", "type": "u8", "offset": 4}, {"name": "frontWideCamera", "type": "u8", "offset": 5}, {"name": "sectionCursor", "type": "u8", "offset": 6}, {"name": "sectionSelector", "type": "u8", "offset": 7}, {"name": "downloadedMaps", "type": "u8", "offset": 8}, {"name": "securityHatchLevel", "type": "u8", "offset": 9}, {"name": "mapScanLRAndStereo", "type": "u8", "offset": 10}], "loc": "include/structs/menus/boot_debug.h:6"}, {"name": "BootDebugOptions__bld__split", "size": 4, "vars": [{"name": "cnt", "type": "u16", "offset": 0}, {"name": "alpha_evb", "type": "u8", "offset": 2}, {"name": "alpha_eva", "type": "u8", "offset": 3}], "loc": "include/structs/menus/boot_debug.h:8"}, {"name": "BootDebugOptions__bld__whole", "size": 4, "vars": [{"name": "cnt", "type": "u16", "offset": 0}, {"name": "alpha", "type": "u16", "offset": 2}], "loc": "include/structs/menus/boot_debug.h:13"}, {"name": "BrokenBlock", "size": 4, "vars": [{"name": "stage", "type": "u8", "offset": 0, "bits": 4}, {"name": "type", "type": "BlockType", "offset": 0, "bits": 4}, {"name": "timer", "type": "u8", "offset": 1}, {"name": "xPosition", "type": "u8", "offset": 2}, {"name": "yPosition", "type": "u8", "offset": 3}], "loc": "include/structs/block.h:15"}, {"name": "ButtonAssignments", "size": 8, "vars": [{"name": "armMissiles", "type": "u16", "offset": 0}, {"name": "diagonalAim", "type": "u16", "offset": 2}, {"name": "swapMissiles", "type": "u16", "offset": 4}, {"name": "pause", "type": "u16", "offset": 6}], "loc": "include/globals.h:228"}, {"name": "Camera", "size": 16, "vars": [{"name": "xPosition", "type": "u16", "offset": 0}, {"name": "prevXPosition", "type": "u16", "offset": 2}, {"name": "yPosition", "type": "u16", "offset": 4}, {"name": "xVelocity", "type": "s8", "offset": 6}, {"name": "yVelocity", "type": "s8", "offset": 7}, {"name": "frontWideDirection", "type": "s8", "offset": 8}, {"name": "ladderFrontWideDirection", "type": "s8", "offset": 9}, {"name": "frontWideXVelocity", "type": "s8", "offset": 10}, {"name": "frontWideTargetXPosition", "type": "u16", "offset": 12}], "loc": "include/structs/scroll.h:58"}, {"name": "CameraScrollVelocityCaps", "size": 8, "vars": [{"name": "leftCap", "type": "s16", "offset": 0}, {"name": "rightCap", "type": "s16", "offset": 2}, {"name": "upCap", "type": "s16", "offset": 4}, {"name": "downCap", "type": "s16", "offset": 6}], "loc": "include/structs/scroll.h:76"}, {"name": "ClipdataBlockData", "size": 12, "vars": [{"name": "xPosition", "type": "u16", "offset": 0}, {"name": "yPosition", "type": "u16", "offset": 2}, {"name": "behavior", "type": "u16", "offset": 4}, {"name": "tilemapValue", "type": "u16", "offset": 6}, {"name": "blockBehavior", "type": "u8", "offset": 8}], "loc": "include/structs/block.h:23"}, {"name": "CollisionData", "size": 28, "vars": [{"name": "type", "type": "u32", "offset": 0}, {"name": "subPixelX", "type": "s32", "offset": 4}, {"name": "subPixelY", "type": "s32", "offset": 8}, {"name": "unk_C", "type": "u32", "offset": 12}, {"name": "unk_10", "type": "u16", "offset": 16}, {"name": "unk_12", "type": "u16", "offset": 18}, {"name": "actor", "type": "s32", "offset": 20}, {"name": "tileX", "type": "u16", "offset": 24}, {"name": "tileY", "type": "u16", "offset": 26}], "loc": "include/structs/clipdata.h:8"}, {"name": "ColorFading", "size": 8, "vars": [{"name": "type", "type": "ColorFadingEffect", "offset": 0}, {"name": "stage", "type": "u8", "offset": 1}, {"name": "fadeTimer", "type": "u8", "offset": 2}, {"name": "unk_3", "type": "u8", "offset": 3}, {"name": "status", "type": "ColorFadingStatus", "offset": 4}, {"name": "usePalette3", "type": "u8", "offset": 5, "bits": 4}, {"name": "unk_5_4", "type": "u8", "offset": 5, "bits": 4}, {"name": "workTimer", "type": "u16", "offset": 6}], "loc": "include/structs/color_effects.h:10"}, {"name": "ColorFadingColorInfo", "size": 8, "vars": [{"name": "colorArray", "type": "const u8* const", "offset": 0}, {"name": "size", "type": "u8", "offset": 4}], "loc": "include/structs/color_effects.h:21"}, {"name": "ColorMultiplier", "size": 12, "vars": [{"name": "red", "type": "s32", "offset": 0}, {"name": "green", "type": "s32", "offset": 4}, {"name": "blue", "type": "s32", "offset": 8}], "loc": "include/structs/color_effects.h:26"}, {"name": "CreditsEntry", "size": 36, "vars": [{"name": "type", "type": "CreditLineType", "offset": 0}, {"name": "text", "type": "u8", "count": 35, "offset": 1}], "loc": "include/structs/ending.h:8"}, {"name": "CurrentAffectingClipdata", "size": 4, "vars": [{"name": "movement", "type": "u16", "offset": 0}, {"name": "hazard", "type": "u16", "offset": 2}], "loc": "include/structs/clipdata.h:26"}, {"name": "DefaultTransparency", "size": 8, "vars": [{"name": "unk_0", "type": "u8", "offset": 0}, {"name": "evbCoef", "type": "u8", "offset": 1}, {"name": "evaCoef", "type": "u8", "offset": 2}, {"name"
